version: 2
jobs:
  awesomebot:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run:
          name: install awesomebot
          command: |
             gem install awesome_bot
      - run:
          name: run awesomebot
          command: |
             awesome_bot contents.json --allow-ssl --allow-redirect -a 403,503,429,404
  json-validate:
    docker:
     - image: cimg/python:3.10.0


    steps:
      - checkout
      - run:
          name: install json-spec
          command: |
            pip install json-spec
      - run: 
          name: run json validate
          command: |
             json validate --schema-file=.github/schema.json --document-file=contents.json
             
  deploy-awesome-video:
    docker:
      - image: krzemienski/ruby-node-python:latest
    steps:
      - checkout
      - run: 
          name: run README.md gen
          command: |
             ruby .github/convert.rb
      - run: 
          name: run database.json gen
          command: |
             node .github/upgradeDb.js
      - run: 
          name: run copy readme to docs for site gen
          command: |
             cp README.md docs/index.md
      - run: 
          name: run static site gen
          command: |
             mkdocs build
      - run: 
          name: deploy new README
          command: |
            .github/deploy-readme.sh
      - run: 
          name: deploy gh pages
          command: | 
            .github/deploy-ghpages.sh site
            
workflows:
  version: 2
  build:
    jobs:
      - awesomebot
      - json-validate
      - deploy-awesome-video:
          context: org-global
          requires:
            - awesomebot
            - json-validate
          filters:
            branches:
              only: master
